name: jp_screens
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  counter_button: ^1.0.1
  customizable_counter: ^1.0.4
  flutter:
    sdk: flutter
  item_count_number_button: ^1.9.2
  material_design_icons_flutter: ^7.0.7296
  page_transition: ^2.1.0
  toggle_switch: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/backgrounds/
    - assets/details/
    - assets/details/trapez.png
    - assets/grafiken/